name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: 25.2.9519653
          link-to-sdk: false
          
      - uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable
          flutter-version: 1.5.x
      - run: flutter packages get
      - run: flutter build apk --release --target-platform=android-arm64
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
